### PR TITLE
Updates to the precovery page

### PR DESCRIPTION
**Pull request by mjuric**
Hi @ntellis 

My changes are on this branch. I went for simplicity, wanting to make the page familiar to eyes used to look at [forms such as these](https://minorplanetcenter.net//cgi-bin/checkmp.cgi).

I tried things out locally as much as I could (I couldn't get it to run API calls because of CORS); hope you can try it out and deploy if it works (feel free to fix any obvious bugs).

Two known issues:
* I replaced the B612 ADAM with an "Asteroid Institute" logo I stole from our Twitter. It doesn't work with this background combination, tough. @B612Remy , you said you had someone who could tweak the design?
* For the NOIRLab Source Catalog, I have "XXX" for the number of observation we search -- @moeyensj , can you give Nate that number?

### CODE REVIEW

**Comment by mjuric** [comment]
Note -- the two noted issues are not showstoppers for merging w. master (assuming it works!).

**Comment by mjuric** [comment]
@ntellis -- one more thing that I didn't know how to accomplish: can the navbar on top be reduced in height by about 50% -- right now there's a lot of unused between the logos/menu items and when the body of the page (the white background) begins. I tried changing `height` in `#heroPrecovery` in App.css to small values (left it at 10vh), but looks like under ~15vh something else is preventing it from becoming smaller.

image

**Comment by B612Remy** [comment]
Adding Merel.


-- 

Danica Remy

President     | B612

Co-Founder | Asteroid Day

e: ***@***.*** ***@***.*** c: 415-710-5288 o:
650-644-4539



[data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACwAAAAAAQABAAACAkQBADs=3D]

**Comment by ntellis** [comment]
@mjuric Added a fix for the hero height on Precovery page, and made the scroll transition more consistent. Merging now

The hero was inheriting the Section CSS, with its padding.

Now the scroll behavior (making the header bg opaque, changing text color accordingly) will trigger on a combination of the hero and header heights, so the transition occurs when the page scrolls past the hero bottom border.

**Comment by B612Remy** [comment]
Call me clueless but this sounds good ;-)


-- 

Danica Remy

President     | B612

Co-Founder | Asteroid Day

e: ***@***.*** ***@***.*** c: 415-710-5288 o:
650-644-4539



[data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACwAAAAAAQABAAACAkQBADs=3D]

**Pull request merged**
